[build]
  # 纯静态网站无需构建命令
  command = ""
  # 发布根目录下的所有文件
  publish = "."

# 配置代理规则，合并所有请求方法
[[redirects]]
  from = "/github-pages"
  to = "https://xfchd090909.github.io/aetck/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "OPTIONS"]  # 明确允许的方法
  [redirects.headers]
    Access-Control-Allow-Origin = "https://aetck.dpdns.org"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    # 如果需要传递cookie等凭证，取消下面这行的注释
    # Access-Control-Allow-Credentials = "true"
